// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njrvfhjlfbktzyvdlxvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcnZmaGpsZmJrdHp5dmRseHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDAxNzIsImV4cCI6MjA2MTI3NjE3Mn0.EurHDe2Yh11BzXUBbKXUVbj-cBiK4IB1Z9gEH7zQy98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);